# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnrapp', '0002_auto_20161015_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='categorty',
            new_name='category',
        ),
    ]
