# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnrapp', '0002_auto_20161016_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuser',
            name='output',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='publicuser',
            name='text',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
